### ISSUE TITLE
Fix pymecompress packaging for py3.x on windows

### ISSUE THREAD

**Issue by David-Baddeley** [python-microscopy/pyme-conda-recipes#1]
pymecompress currently does not build well on windows for python3. This is down to the use of gcc, and associated linking headaches with libpython (specifically that anaconda doesn't package libpythonXX.a, or this can't be found when it comes to link time).

**Comment by David-Baddeley** [comment]
we've hacked around this on py2 by shipping libpython27.a in the repo (ugh), but ideally there'd be a cleaner solution.

**Comment by barentine** [comment]
Does build well mean doesn't build, or builds? On windows 3 we had to 

## 1. install the following Visual Studio Build Tools 2019:

### Included

C++ Build Tools core features
 
C++ 2019 Redistributable Update
Optional

MSVC v142 - VS 2019 C++ x64/x86 build tools (v14.21)
 
Windows 10 SDK (10.0.17763.0)
 
C++ CMake tools for Windows
 
Testing tools core features - Build Tools
 
Windows 10 SDK (10.0.17134.0)
 
MSVC v140 - VS 2015 C++ build tools (v14.00)

### Individual components

Windows Universal C Runtime
 
Windows Universal CRT SDK
 
MSVC v140 - VS 2015 C++ build tools (v14.00)
 
NuGet targets and build tasks
 
.NET Framework 4.6 targeting pack
 
Visual Studio SDK Build Tools Core

## 2. build extension in place
Run `\pymecompress>python setup.py build_ext -i -c mingw32` before running `python setup.py develop` or `python setup.py install`

**Comment by David-Baddeley** [comment]
Should have closed this - pymecompress now builds fine (only needs mingw,
but loads of distutils monkey patching)
